using MailArchiver.Data;
using MailArchiver.Utilities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace MailArchiver.Services;

public sealed class EncryptionMigrationHostedService : IHostedService
{
    private readonly IServiceProvider _serviceProvider;
    private readonly ILogger<EncryptionMigrationHostedService> _logger;

    public EncryptionMigrationHostedService(
        IServiceProvider serviceProvider,
        ILogger<EncryptionMigrationHostedService> logger)
    {
        _serviceProvider = serviceProvider;
        _logger = logger;
    }

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        try
        {
            using var scope = _serviceProvider.CreateScope();
            var configuration = scope.ServiceProvider.GetRequiredService<IConfiguration>();

            var connectionString =
                configuration.GetConnectionString("DefaultConnection") ??
                configuration["ConnectionStrings:DefaultConnection"] ??
                configuration["DATABASE_URL"];

            if (string.IsNullOrWhiteSpace(connectionString))
            {
                _logger.LogWarning("Encryption migration skipped because no database connection string was found.");
                return;
            }

            await using var connection = new NpgsqlConnection(connectionString);
            await connection.OpenAsync(cancellationToken);

            var schema = await ResolvePrimarySchemaAsync(connection, cancellationToken);

            await EnsureSchemaCompatibilityAsync(connection, schema, cancellationToken);
            await EnsureDeletedEmailMarkersTableAsync(connection, schema, cancellationToken);
            await MigrateArchivedEmailsAsync(connection, schema, cancellationToken);
            await MigrateAttachmentsAsync(connection, schema, cancellationToken);
            await MigrateSensitiveSecretsAsync(cancellationToken);

            _logger.LogInformation("Encryption migration completed.");
        }
        catch (OperationCanceledException)
        {
            _logger.LogInformation("Encryption migration was cancelled.");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Encryption migration failed. Application startup will continue.");
        }
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    private async Task EnsureSchemaCompatibilityAsync(
        NpgsqlConnection connection,
        string schema,
        CancellationToken cancellationToken)
    {
        if (await TableExistsAsync(connection, schema, "ArchivedEmails", cancellationToken))
        {
            await EnsureColumnExistsAsync(connection, schema, "ArchivedEmails", "OriginalBodyText", "bytea", cancellationToken);
            await EnsureColumnExistsAsync(connection, schema, "ArchivedEmails", "OriginalBodyHtml", "bytea", cancellationToken);
            await EnsureColumnExistsAsync(connection, schema, "ArchivedEmails", "BodySearchText", "text NOT NULL DEFAULT ''", cancellationToken);
        }

        if (await TableExistsAsync(connection, schema, "EmailAttachments", cancellationToken))
        {
            await EnsureColumnExistsAsync(connection, schema, "EmailAttachments", "OriginalContent", "bytea", cancellationToken);
        }
    }

    private async Task EnsureDeletedEmailMarkersTableAsync(
        NpgsqlConnection connection,
        string schema,
        CancellationToken cancellationToken)
    {
        var sql = $@"
CREATE TABLE IF NOT EXISTS ""{schema}"".""DeletedEmailMarkers"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""MailAccountId"" integer NOT NULL,
    ""MessageId"" text NOT NULL DEFAULT '',
    ""From"" text NOT NULL DEFAULT '',
    ""To"" text NOT NULL DEFAULT '',
    ""Subject"" text NOT NULL DEFAULT '',
    ""SentDate"" timestamp with time zone NOT NULL,
    ""DeletedAt"" timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ""IX_DeletedEmailMarkers_MailAccountId_MessageId""
    ON ""{schema}"".""DeletedEmailMarkers"" (""MailAccountId"", ""MessageId"");

CREATE INDEX IF NOT EXISTS ""IX_DeletedEmailMarkers_NaturalKey""
    ON ""{schema}"".""DeletedEmailMarkers"" (""MailAccountId"", ""From"", ""To"", ""Subject"", ""SentDate"");
";

        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    private async Task MigrateArchivedEmailsAsync(
        NpgsqlConnection connection,
        string schema,
        CancellationToken cancellationToken)
    {
        if (!await TableExistsAsync(connection, schema, "ArchivedEmails", cancellationToken))
        {
            _logger.LogInformation("ArchivedEmails table not found. Skipping archived email migration.");
            return;
        }

        var hasBodyText = await ColumnExistsAsync(connection, schema, "ArchivedEmails", "BodyText", cancellationToken);
        var hasBodyHtml = await ColumnExistsAsync(connection, schema, "ArchivedEmails", "BodyHtml", cancellationToken);
        var hasOriginalBodyText = await ColumnExistsAsync(connection, schema, "ArchivedEmails", "OriginalBodyText", cancellationToken);
        var hasOriginalBodyHtml = await ColumnExistsAsync(connection, schema, "ArchivedEmails", "OriginalBodyHtml", cancellationToken);
        var hasBodySearchText = await ColumnExistsAsync(connection, schema, "ArchivedEmails", "BodySearchText", cancellationToken);

        var setClauses = new List<string>();
        var whereConditions = new List<string>();

        if (hasBodyText && hasOriginalBodyText)
        {
            setClauses.Add(@"""OriginalBodyText"" = CASE
    WHEN ""OriginalBodyText"" IS NULL AND ""BodyText"" IS NOT NULL
        THEN convert_to(""BodyText"", 'UTF8')
    ELSE ""OriginalBodyText""
END");

            whereConditions.Add(@"(""OriginalBodyText"" IS NULL AND ""BodyText"" IS NOT NULL)");
        }

        if (hasBodyHtml && hasOriginalBodyHtml)
        {
            setClauses.Add(@"""OriginalBodyHtml"" = CASE
    WHEN ""OriginalBodyHtml"" IS NULL AND ""BodyHtml"" IS NOT NULL
        THEN convert_to(""BodyHtml"", 'UTF8')
    ELSE ""OriginalBodyHtml""
END");

            whereConditions.Add(@"(""OriginalBodyHtml"" IS NULL AND ""BodyHtml"" IS NOT NULL)");
        }

        if (setClauses.Count > 0)
        {
            var migrateSql = $@"
UPDATE ""{schema}"".""ArchivedEmails""
SET
    {string.Join(",\n    ", setClauses)}
WHERE
    {string.Join("\n    OR ", whereConditions)};";

            await using var command = new NpgsqlCommand(migrateSql, connection);
            var updated = await command.ExecuteNonQueryAsync(cancellationToken);

            _logger.LogInformation("ArchivedEmails migration updated {Count} row(s).", updated);
        }
        else
        {
            _logger.LogInformation("No compatible ArchivedEmails columns found for migration.");
        }

        await CleanupArchivedEmailsAsync(connection, schema, hasBodyText, hasBodyHtml, hasBodySearchText, cancellationToken);
    }

    private async Task CleanupArchivedEmailsAsync(
        NpgsqlConnection connection,
        string schema,
        bool hasBodyText,
        bool hasBodyHtml,
        bool hasBodySearchText,
        CancellationToken cancellationToken)
    {
        var cleanupClauses = new List<string>();
        var whereConditions = new List<string>();

        if (hasBodyText)
        {
            cleanupClauses.Add(@"""BodyText"" = NULL");
            whereConditions.Add(@"""BodyText"" IS NOT NULL");
        }

        if (hasBodyHtml)
        {
            cleanupClauses.Add(@"""BodyHtml"" = NULL");
            whereConditions.Add(@"""BodyHtml"" IS NOT NULL");
        }

        if (hasBodySearchText)
        {
            cleanupClauses.Add(@"""BodySearchText"" = ''");
            whereConditions.Add(@"""BodySearchText"" IS DISTINCT FROM ''");
        }

        if (cleanupClauses.Count == 0)
        {
            _logger.LogInformation("No legacy ArchivedEmails columns found for cleanup.");
            return;
        }

        var cleanupSql = $@"
UPDATE ""{schema}"".""ArchivedEmails""
SET
    {string.Join(",\n    ", cleanupClauses)}
WHERE
    {string.Join("\n    OR ", whereConditions)};";

        await using var command = new NpgsqlCommand(cleanupSql, connection);
        var cleaned = await command.ExecuteNonQueryAsync(cancellationToken);

        _logger.LogInformation("ArchivedEmails cleanup updated {Count} row(s).", cleaned);
    }

    private async Task MigrateAttachmentsAsync(
        NpgsqlConnection connection,
        string schema,
        CancellationToken cancellationToken)
    {
        if (!await TableExistsAsync(connection, schema, "EmailAttachments", cancellationToken))
        {
            _logger.LogInformation("EmailAttachments table not found. Skipping attachment migration.");
            return;
        }

        var hasContent = await ColumnExistsAsync(connection, schema, "EmailAttachments", "Content", cancellationToken);
        var hasOriginalContent = await ColumnExistsAsync(connection, schema, "EmailAttachments", "OriginalContent", cancellationToken);

        if (!hasContent || !hasOriginalContent)
        {
            _logger.LogInformation("Attachment migration skipped because required columns are missing.");
            return;
        }

        var sql = $@"
UPDATE ""{schema}"".""EmailAttachments""
SET ""OriginalContent"" = CASE
    WHEN ""OriginalContent"" IS NULL AND ""Content"" IS NOT NULL
        THEN ""Content""
    ELSE ""OriginalContent""
END
WHERE ""OriginalContent"" IS NULL AND ""Content"" IS NOT NULL;";

        await using var command = new NpgsqlCommand(sql, connection);
        var updated = await command.ExecuteNonQueryAsync(cancellationToken);

        _logger.LogInformation("EmailAttachments migration updated {Count} row(s).", updated);
    }

    private async Task MigrateSensitiveSecretsAsync(CancellationToken cancellationToken)
    {
        using var scope = _serviceProvider.CreateScope();
        var context = scope.ServiceProvider.GetRequiredService<MailArchiverDbContext>();

        var migratedAccountFields = 0;
        var candidateAccounts = await context.MailAccounts
            .Where(a => !string.IsNullOrEmpty(a.Password) || !string.IsNullOrEmpty(a.ClientSecret))
            .ToListAsync(cancellationToken);

        var accounts = candidateAccounts
            .Where(a =>
                (!string.IsNullOrEmpty(a.Password) && !EmailEncryption.IsEncryptedString(a.Password)) ||
                (!string.IsNullOrEmpty(a.ClientSecret) && !EmailEncryption.IsEncryptedString(a.ClientSecret)))
            .ToList();

        foreach (var account in accounts)
        {
            if (!string.IsNullOrEmpty(account.Password) && !EmailEncryption.IsEncryptedString(account.Password))
            {
                context.Entry(account).Property(a => a.Password).IsModified = true;
                migratedAccountFields++;
            }

            if (!string.IsNullOrEmpty(account.ClientSecret) && !EmailEncryption.IsEncryptedString(account.ClientSecret))
            {
                context.Entry(account).Property(a => a.ClientSecret).IsModified = true;
                migratedAccountFields++;
            }
        }

        var migratedUserFields = 0;
        var candidateUsers = await context.Users
            .Where(u => !string.IsNullOrEmpty(u.TwoFactorSecret))
            .ToListAsync(cancellationToken);

        var users = candidateUsers
            .Where(u => !string.IsNullOrEmpty(u.TwoFactorSecret) && !EmailEncryption.IsEncryptedString(u.TwoFactorSecret))
            .ToList();

        foreach (var user in users)
        {
            context.Entry(user).Property(u => u.TwoFactorSecret).IsModified = true;
            migratedUserFields++;
        }

        if (migratedAccountFields == 0 && migratedUserFields == 0)
        {
            _logger.LogInformation("No legacy plaintext secrets required encryption migration.");
            return;
        }

        await context.SaveChangesAsync(cancellationToken);
        _logger.LogInformation(
            "Sensitive secret migration re-encrypted {AccountFieldCount} mail account field(s) and {UserFieldCount} user field(s).",
            migratedAccountFields,
            migratedUserFields);
    }

    private static async Task<string> ResolvePrimarySchemaAsync(
        NpgsqlConnection connection,
        CancellationToken cancellationToken)
    {
        if (await TableExistsAsync(connection, "mail_archiver", "ArchivedEmails", cancellationToken))
        {
            return "mail_archiver";
        }

        if (await TableExistsAsync(connection, "public", "ArchivedEmails", cancellationToken))
        {
            return "public";
        }

        return "mail_archiver";
    }

    private static async Task<bool> TableExistsAsync(
        NpgsqlConnection connection,
        string schema,
        string tableName,
        CancellationToken cancellationToken)
    {
        const string sql = """
SELECT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = @schema
      AND table_name = @tableName
);
""";

        await using var command = new NpgsqlCommand(sql, connection);
        command.Parameters.AddWithValue("schema", schema);
        command.Parameters.AddWithValue("tableName", tableName);

        var result = await command.ExecuteScalarAsync(cancellationToken);
        return result is bool exists && exists;
    }

    private static async Task<bool> ColumnExistsAsync(
        NpgsqlConnection connection,
        string schema,
        string tableName,
        string columnName,
        CancellationToken cancellationToken)
    {
        const string sql = """
SELECT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = @schema
      AND table_name = @tableName
      AND column_name = @columnName
);
""";

        await using var command = new NpgsqlCommand(sql, connection);
        command.Parameters.AddWithValue("schema", schema);
        command.Parameters.AddWithValue("tableName", tableName);
        command.Parameters.AddWithValue("columnName", columnName);

        var result = await command.ExecuteScalarAsync(cancellationToken);
        return result is bool exists && exists;
    }

    private async Task EnsureColumnExistsAsync(
        NpgsqlConnection connection,
        string schema,
        string tableName,
        string columnName,
        string postgresType,
        CancellationToken cancellationToken)
    {
        if (await ColumnExistsAsync(connection, schema, tableName, columnName, cancellationToken))
        {
            return;
        }

        var sql = $@"
ALTER TABLE ""{schema}"".""{tableName}""
ADD COLUMN ""{columnName}"" {postgresType};";

        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync(cancellationToken);

        _logger.LogInformation("Created missing column {Schema}.{Table}.{Column} ({Type}).", schema, tableName, columnName, postgresType);
    }
}
